version: "3.9"
services:
  addressbook:
    network_mode: ipsec_strongswan_docker_automated_connection_myvpnnetwork
    build:
      context: .
    # ports:
    #   - '3000:3000'
        
volumes:
  addressbook-db:

networks:
  ipsec_strongswan_docker_automated_connection_myvpnnetwork:
    external:
      name: ipsec_strongswan_docker_automated_connection_myvpnnetwork